### ISSUE TITLE
Handling absolute path

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#135]
@alexeid 
The current `readNexus(file=,..)` relies on LPhy Studio starting in the parent folder of scripts, when the Nexus file is using a relative path. If we are going to support the absolute path for scripts, a reference path has to be defined for Nexus file (script path and nexus path are in two different places). I suggest to use `user.dir`.

So I am going to make the following updates:
1.If a script is loaded, set `user.dir` to the folder containing the script.
2. If no script, e.g. console, then encourage users to use the absolute path to `readNexus(file=,..)`, or we could add `setWD()` in future.
3. For any I/O in LPhy, such as `readNexus(file=,..)`, check if the `file` is a relative or absolute path, if relative, then concatenate `user.dir` before the relative path.

**Comment by walterxie** [comment]
Important changes:
1. Every time after loading a script file, LPhy Studio will set `user.dir` to the folder containing this file. This folder will be used as the reference when the data path inside the scrips is a relative path. This is done in `readFile()` in `LPhySudio` and `test_ThatXmlExamplesRun()` in `ParserTest`. 
2. So, for LPhy script, the relative path is always referring to the folder where it is. Then the data can be easily organized with the scripts together. Please see `tutorials/RSV2.lphy` and `examples/fullDataExample.lphy`, etc.

**Comment by walterxie** [comment]
IntelliJ config:

![absolute](https://user-images.githubusercontent.com/5743014/115487018-eaf58b80-a2ab-11eb-86bd-7b3b5573d94b.png)

![relative](https://user-images.githubusercontent.com/5743014/115487031-ee891280-a2ab-11eb-8411-04f9112f2f4b.png)

**Comment by walterxie** [comment]
LinguaPhylo/LPhyBeast#36

**Comment by walterxie** [comment]
NullPointerException:

at lphy.utils.IOUtils.setUserDir(Unknown Source)
at lphy.app.LinguaPhyloStudio.readFile(Unknown Source)
