### ISSUE TITLE
Node count function produces Exception

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#160]
Using the `nodecount()` function in an lphy script produces an exception `java.lang.UnsupportedOperationException`

Example script: https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/yuleRelaxed.lphy
Program arguments: -r 1 -l 3000000 ../linguaPhylo/examples/yuleRelaxed.lphy

Stack trace:
```
java.lang.UnsupportedOperationException: Unhandled generator in generatorToBEAST(): class lphy.core.functions.NodeCount
	at lphybeast.BEASTContext.generatorToBEAST(BEASTContext.java:628)
	at lphybeast.BEASTContext.traverseBEASTGeneratorObjects(BEASTContext.java:583) 
	...
	at lphybeast.LPhyBEAST.main(LPhyBEAST.java:66)
```

One possible solution is to add the node count function as an excluded generator to the Exclusions list 
https://github.com/kche309/LPhyBeast/commit/541d517537e986d27e77bb82f7392ab11c3d0a5f

**Comment by kche309** [comment]
Please ignore this Git Issue.

This Git Issue has been moved to https://github.com/LinguaPhylo/LPhyBeast/issues/56
