### ISSUE TITLE
Add about menu to show credits

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#173]
Add about menu to show credits

**Comment by walterxie** [comment]
Not tested in Win and Linux.

**Comment by kche309** [comment]
Testing lphystudio on Windows 10 using the test release https://github.com/LinguaPhylo/linguaPhylo/releases/tag/untagged-aa87882221786b1382bb produces the following error message:
```
Exception in thread "main" java.lang.UnsupportedOperationException: The APP_ABOUT action is not supported on the current platform!
        at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
        at java.desktop/java.awt.Desktop.setAboutHandler(Desktop.java:706)
        at lphystudio@1.3.0-SNAPSHOT/lphystudio.app.LinguaPhyloStudio.<init>(LinguaPhyloStudio.java:156)
        at lphystudio@1.3.0-SNAPSHOT/lphystudio.app.LinguaPhyloStudio.main(LinguaPhyloStudio.java:397)
```

**Comment by walterxie** [comment]
What Java version?

**Comment by kche309** [comment]
I'm running openjdk 17 on Windows, java --version output is:
```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

**Comment by kche309** [comment]
I am also getting a similar message on Ubuntu 20.04 when running the test release [LPhy v1.3.0](https://github.com/LinguaPhylo/linguaPhylo/releases/tag/untagged-aa87882221786b1382bb) 

OS: Ubuntu 20.04.4 LTS (Focal Fossa)
Graphical user-interface: XDG_CURRENT_DESKTOP=ubuntu:GNOME
Java version: openjdk version "17.0.3" 2022-04-19

```
Exception in thread "main" java.lang.UnsupportedOperationException: The APP_ABOUT action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
	at java.desktop/java.awt.Desktop.setAboutHandler(Desktop.java:706)
	at lphystudio@1.3.0-SNAPSHOT/lphystudio.app.LinguaPhyloStudio.<init>(LinguaPhyloStudio.java:156)
	at lphystudio@1.3.0-SNAPSHOT/lphystudio.app.LinguaPhyloStudio.main(LinguaPhyloStudio.java:397)
```
