### ISSUE TITLE
Parser did not catch the err of having no ;

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#234]
Type `a = abs(-1)` without `;`, the Exception should throw from Parser not LineCodeColorizer:

```java
SEVERE: CodeColorizer failed with exception: Cannot invoke "org.antlr.v4.runtime.RecognitionException.printStackTrace()" because "e" is null
java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.RecognitionException.printStackTrace()" because "e" is null
	at lphystudio/lphystudio.core.codecolorizer.LineCodeColorizer$1.syntaxError(LineCodeColorizer.java:342)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.DefaultErrorStrategy.reportMissingToken(DefaultErrorStrategy.java:409)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenInsertion(DefaultErrorStrategy.java:519)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:476)
	at org.antlr.antlr4.runtime@4.9.3/org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at lphy/lphy.parser.SimulatorParser.relation(SimulatorParser.java:351)
	at lphy/lphy.parser.SimulatorParser.relation_list(SimulatorParser.java:262)
	at lphy/lphy.parser.SimulatorParser.input(SimulatorParser.java:153)
	at lphystudio/lphystudio.core.codecolorizer.LineCodeColorizer.parse(LineCodeColorizer.java:377)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelInterpreter.interpretInput(GraphicalModelInterpreter.java:235)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelInterpreter.lambda$new$0(GraphicalModelInterpreter.java:100)
```

**Comment by walterxie** [comment]
This is caused by no consistency using parsers (too many parsers, very confusing). 

There is a ";" check in `REPL`. The preprocess will add ";" if "cmd" does not end with ";".

https://github.com/LinguaPhylo/linguaPhylo/blob/d9c49b28aa996c4ed08074f92c2ef439f8e8533f/lphy/src/main/java/lphy/parser/REPL.java#L98-L107

But in LPhy studio the LineCodeColorizer parses "input" (cmd) again, after LPhyParser parses "input". Both have no preprocess about ";". 

https://github.com/LinguaPhylo/linguaPhylo/blob/d9c49b28aa996c4ed08074f92c2ef439f8e8533f/lphy-studio/src/main/java/lphystudio/app/graphicalmodelpanel/GraphicalModelInterpreter.java#L230-L235

**Comment by walterxie** [comment]
It'd better to have one parser, and one place to preprocess ";".

**Comment by walterxie** [comment]
This bug is fixed. But the recommended solutions are #235 and #236.

**Comment by walterxie** [comment]
if no `data{}`, input is empty
