### ISSUE TITLE
Unit test in Github OutOfMemoryError

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#262]
```java
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 1.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
...
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at lphy.evolution.tree.TimeTreeNode.<init>(TimeTreeNode.java:22)
	at lphy.evolution.birthdeath.FullBirthDeathTree.doBirth(FullBirthDeathTree.java:140)
	at lphy.evolution.birthdeath.FullBirthDeathTree.sample(FullBirthDeathTree.java:110)
	at lphy.evolution.birthdeath.BirthDeathSamplingTree.sample(BirthDeathSamplingTree.java:52)
...
```

**Comment by walterxie** [comment]
set maxHeapSize = "3G", but GitHub still fails. The local machine only consumes few hundreds MB. It is most likely Github Action has bug again.

**Comment by walterxie** [comment]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v2.

Upgrade to v3

**Comment by walterxie** [comment]
temporarily disable test

**Comment by walterxie** [comment]
Why Github Action so buggy :

<img width="740" alt="Screen Shot 2023-01-31 at 10 53 20 AM" src="https://user-images.githubusercontent.com/5743014/215603796-0d206e15-2c8e-4cab-8446-ae4afcca8ddc.png">
