### ISSUE TITLE
simulate function is broken

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#267]
Run `-d examples/simulation jcCoal.lphy`    https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/simulation/jcCoal.lphy

Jan 31, 2023 2:24:54 PM lphy.parser.ParserUtils constructGenerator
SEVERE: Parsing generator simulate failed.
Jan 31, 2023 2:24:54 PM lphy.parser.ParserUtils constructGenerator
SEVERE: Parsing generator simulate failed.
```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "lphy.graphicalModel.Generator.setInput(String, lphy.graphicalModel.Value)" because "generator" is null
	at lphy/lphy.parser.SimulatorListenerImpl$SimulatorASTVisitor.visitMethodCall(SimulatorListenerImpl.java:857)
	at lphy/lphy.parser.SimulatorParser$MethodCallContext.accept(SimulatorParser.java:1125)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy/lphy.parser.SimulatorBaseVisitor.visitExpression(SimulatorBaseVisitor.java:161)
...
```

**Comment by walterxie** [comment]
#260

**Comment by walterxie** [comment]
<img width="701" alt="Screen Shot 2023-01-31 at 3 32 59 PM" src="https://user-images.githubusercontent.com/5743014/215647886-226d6d14-be83-4706-acbf-c698fae85c64.png">

**Comment by walterxie** [comment]
#268
