### ISSUE TITLE
Array's ID shows 1 and inline function ID is null

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#278]
Array's ID looks always to be 1 somehow. This affects the narrative as well:

such as "A 1 is assumed to", and "1, const. The 1, const is assumed", ...

Also inline function ID is null.

**Comment by walterxie** [comment]
<img width="1369" alt="Screenshot 2023-02-21 at 2 41 09 PM" src="https://user-images.githubusercontent.com/5743014/220226405-705a1ff1-39be-4fa9-9af2-b8aa2cbbd726.png">

**Comment by walterxie** [comment]
This will affect LPhyBEAST as well, such as : 

```java
java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "<parameter1>" is null
	at java.base/java.util.TreeMap.compare(Unknown Source)
	at java.base/java.util.TreeMap.addEntryToEmptyMap(Unknown Source)
	at java.base/java.util.TreeMap.put(Unknown Source)
	at java.base/java.util.TreeMap.put(Unknown Source)
	at lphy.core.Sampler.getNewlySampledParams(Sampler.java:83)
	at lphy.core.Sampler.sampleAll(Sampler.java:60)
	at lphy.core.Sampler.getNewlySampledParams(Sampler.java:81)
	at lphy.core.Sampler.sampleAll(Sampler.java:60)
```

lphy.core.Sampler:
```java
        for (Map.Entry<String, Value> e : params.entrySet()) {
            Value val = e.getValue();
            if (val.isRandom()) {
                if (val.isAnonymous() || !sampled.contains(val.getId())) {
                    ...
                    newlySampledParams.put(**e.getKey()**, nv);
```

**Comment by walterxie** [comment]
<img width="553" alt="Screenshot 2023-02-23 at 1 08 38 PM" src="https://user-images.githubusercontent.com/5743014/220810252-1514bf6d-0241-471c-a39d-a8d399a5dfd0.png">
