### ISSUE TITLE
FileSystemNotFoundException

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#282]
```java
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at lphystudio@1.4.1-SNAPSHOT/lphystudio.app.LPhyAppConfig.getLPhyIcon(LPhyAppConfig.java:56)
	at lphystudio@1.4.1-SNAPSHOT/lphystudio.app.LinguaPhyloStudio.<clinit>(LinguaPhyloStudio.java:46)
```

**Comment by walterxie** [comment]
Get InputStream from getResourceAsStream
