### ISSUE TITLE
Improve the parser err message

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#292]
Improve the parser err message for lphy grammar err. 

E.g.  https://github.com/LinguaPhylo/linguaPhylo/blob/973af6cc6ce0a5bbcc942063637fbfb9761e5f85/examples/simulation/jcCoal.lphy#L12-L13

If mis is mistyped to `mi`, where `mi` does exist, it will throw Exception instead of a parsing err:
```
mis = get(key="mis", map=D);
l = length(mis1);
```

```java
Exception in thread "main" java.lang.RuntimeException: ERROR! No match in length constructor arguments, including vector match! 
	at lphy/lphy.parser.ParserUtils.constructGenerator(ParserUtils.java:183)
	at lphy/lphy.parser.ParserUtils.getFunctionByArguments(ParserUtils.java:150)
	at lphy/lphy.parser.ParserUtils.getMatchingFunctions(ParserUtils.java:53)
	at lphy/lphy.parser.SimulatorListenerImpl$SimulatorASTVisitor.visitMethodCall(SimulatorListenerImpl.java:852)
	at lphy/lphy.parser.SimulatorParser$MethodCallContext.accept(SimulatorParser.java:1125)

```

**Comment by walterxie** [comment]
#346

**Comment by walterxie** [comment]
Some ideas:
1. create some specified Exception to handle and report different types of errors;
2. interpret ANTRL error to make it understandable to both users and developers;
3. build err handling system on the top of the system, which may require to pass the Exceptions from the base classes to the high level classes.

More ideas?

**Comment by walterxie** [comment]
In `GraphicalModelInterpreter` `public void interpretInput(String input, LPhyParser.Context context) {` is the current place to catch the exceptions to display to err panel using `LoggerUtils.log`. But there are few more place to handle exceptions for non-GUI situation. 

https://github.com/LinguaPhylo/linguaPhylo/blob/3c22572b3ffd836a6a9671eb612eeb11560d810c/lphy-studio/src/main/java/lphystudio/app/graphicalmodelpanel/GraphicalModelInterpreter.java#L265-L286
