### ISSUE TITLE
RuntimeException: Expected VectorizedRandomVariable

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#302]
Load tutorial => RSV2

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Expected VectorizedRandomVariable!
	at lphy/lphy.core.distributions.VectorizedDistribution.getInferenceNarrative(VectorizedDistribution.java:121)
	at lphy/lphy.graphicalModel.Value.getNarrative(Value.java:86)
	at lphy/lphy.graphicalModel.GraphicalModel$Utils.getNarrative(GraphicalModel.java:250)
	at lphystudio/lphystudio.app.graphicalmodelpanel.NarrativePanel.setText(NarrativePanel.java:369)
	at lphy/lphy.core.GraphicalLPhyParser.notifyListeners(GraphicalLPhyParser.java:87)
	at lphy/lphy.core.GraphicalLPhyParser.parse(GraphicalLPhyParser.java:54)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelInterpreter.interpretInput(GraphicalModelInterpreter.java:235)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelPanel.source(GraphicalModelPanel.java:213)
	at lphystudio/lphystudio.app.Utils.readFile(Utils.java:127)
	at lphystudio/lphystudio.app.Utils.readFileFromDir(Utils.java:101)
	at lphystudio/lphystudio.app.LinguaPhyloStudio.readFile(LinguaPhyloStudio.java:363)
	at lphystudio/lphystudio.app.LinguaPhyloStudio.lambda$createMenuItemForLPhyScript$19(LinguaPhyloStudio.java:481)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:129)
	at java.desktop/java.awt.MenuItem.processActionEvent(MenuItem.java:692)
	at java.desktop/java.awt.MenuItem.processEvent(MenuItem.java:651)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:379)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:367)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Expected VectorizedRandomVariable!
	at lphy/lphy.core.distributions.VectorizedDistribution.getInferenceNarrative(VectorizedDistribution.java:121)
	at lphy/lphy.graphicalModel.Value.getNarrative(Value.java:86)
	at lphy/lphy.graphicalModel.GraphicalModel$Utils.getNarrative(GraphicalModel.java:250)
	at lphystudio/lphystudio.app.graphicalmodelpanel.NarrativePanel.setText(NarrativePanel.java:369)
	at lphystudio/lphystudio.app.graphicalmodelpanel.NarrativePanel$2.layout(NarrativePanel.java:132)
	at lphystudio/lphystudio.app.graphicalmodelcomponent.GraphicalModelComponent.paintComponent(GraphicalModelComponent.java:144)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by walterxie** [comment]
It seems the method call does not produce `VectorizedRandomVariable`, instead it produces `RandomVariable<T[]>`.
