### ISSUE TITLE
Gradle (ServiceLoader) problem to load SPI during tests

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#375]
Gradle problem to load SPI during tests, I think they are Gradle bugs:

1. ElementWise2ArgsTest.test1DPlus2D(ElementWise2ArgsTest.java:55). `Object res = ParserTest.parse("sum = [1.0,2.0,3.0] + [[1.0,2.0,3.0],[3.0,2.0,1.0]];");`. The test is passed, but it throws ServiceConfigurationError. The stranger thing is this test is in the core, which should not require `lphy.base.spi.LPhyBaseImpl ` .

```java
java.util.ServiceConfigurationError: lphy.core.spi.LPhyExtension: Provider lphy.base.spi.LPhyBaseImpl not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at lphy.core.spi.LPhyLoader.registerExtensions(LPhyLoader.java:84)
	at lphy.core.spi.LPhyLoader.<init>(LPhyLoader.java:24)
	at lphy.core.spi.LPhyLoader.getInstance(LPhyLoader.java:30)
	at lphy.core.parser.ParserLoader.<clinit>(ParserLoader.java:29)
	at lphy.core.parser.LPhyListenerImpl$LPhyASTVisitor.visitExpression(LPhyListenerImpl.java:299)
```

2. In the `base`, LPhyExamplesTest cannot find the SequenceType when running "simpleSerialCoalescentNex.lphy" and "twoPartitionCoalescentNex.lphy". It seems another problem for ServiceLoader in Gradle test. 

However, these scripts are **working well** when loading them from studio either in IDE or a released snapshot version.

**Comment by walterxie** [comment]
"covidDPG.lphy", "simpleSerialCoalescentNex.lphy", "twoPartitionCoalescentNex.lphy"

```java
Example simpleSerialCoalescentNex.lphy failed at Exception :
Cannot find the sequence type in SequenceTypeLoader ! DNA
org.opentest4j.AssertionFailedError: Example simpleSerialCoalescentNex.lphy failed at Exception :
Cannot find the sequence type in SequenceTypeLoader ! DNA
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:135)
	at app//lphy.base.LPhyExamplesTest.testLPhyExamplesInDir(LPhyExamplesTest.java:63)
	at app//lphy.base.LPhyExamplesTest.testLPhyExamplesRun(LPhyExamplesTest.java:33)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
```

**Comment by walterxie** [comment]
move the 2nd to #397
