### ISSUE TITLE
ElementWise2ArgsTest.test1DPlus2D test should not look for lphy.base.spi.LPhyBaseImpl

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#414]
The test passed, but it seems `ParserSingleton.parse(cmd)` not working properly:

```java
java.util.ServiceConfigurationError: lphy.core.spi.LPhyExtension: Provider lphy.base.spi.LPhyBaseImpl not found
java.util.ServiceConfigurationError: lphy.core.spi.LPhyExtension: Provider lphy.base.spi.LPhyBaseImpl not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at lphy.core.spi.LPhyCoreLoader.registerExtensions(LPhyCoreLoader.java:61)
	at lphy.core.spi.LPhyCoreLoader.loadAllExtensions(LPhyCoreLoader.java:47)
	at lphy.core.spi.LoaderManager.<clinit>(LoaderManager.java:31)
```

**Comment by walterxie** [comment]
Another bug in `LPhyCoreLoader` to catch `ServiceConfigurationError`:

```java
        } catch (ServiceConfigurationError serviceError) {
            System.err.println(serviceError);
            serviceError.printStackTrace();
        }
```

**Comment by walterxie** [comment]
1. This test is only for the core. After splitting core and moving functions and distributions to base #294, the LPhyCoreLoader should not throw exception when no functions and distributions were loaded. 

2. Catching ServiceConfigurationError is moved to surround `lPhyExt = extensions.next();` only, for the scenario of unit testing at core.
