### ISSUE TITLE
Lphy script throw "Row names 0 must be same to the sample count 1 !" error after pressing Sample button

### ISSUE THREAD

**Issue by EvaLiyt** [LinguaPhylo/linguaPhylo#477]
LPhy script
```
data{
    ψ = readTrees(file="./test3_psi.txt");
}
model{
    //tree ~ Yule(lambda=0.25, n=100);
    tree = ψ[0];
    names = tree.getTaxaNames();

    A ~ PhyloCTMC(L=100, Q=jukesCantor(1.0), tree=tree);
 }
```
After pressing "Sample" on LPhySudio, it throws the error message
[test3_psi.txt](https://github.com/LinguaPhylo/linguaPhylo/files/15371457/test3_psi.txt)

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Row names 0 must be same to the sample count 1 !
	at lphy.core/lphy.core.logger.RandomNumberLoggerListener.replicate(RandomNumberLoggerListener.java:116)
	at lphystudio/lphystudio.core.logger.VariableTextArea.replicate(VariableTextArea.java:42)
	at lphy.core/lphy.core.simulator.Sampler.sampleAll(Sampler.java:145)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelSampler.sampleAll(GraphicalModelSampler.java:34)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelPanel.sample(GraphicalModelPanel.java:297)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelPanel.sample(GraphicalModelPanel.java:278)
	at lphystudio/lphystudio.app.graphicalmodelpanel.GraphicalModelPanel.lambda$new$0(GraphicalModelPanel.java:109)
```

**Comment by kche309** [comment]
I also get this issue only using a Yule tree with a large number of taxa
```
n = 10000;
L = 1000;
λ ~ LogNormal(meanlog=3.0, sdlog=1.0);
ψ ~ Yule(lambda=λ, n=n);
D ~ PhyloCTMC(L=L, Q=jukesCantor(), tree=ψ);
```
