### ISSUE TITLE
Resample birthDeathOnRootAgeAndTaxa.lphy and birthDeathRhoSampling.lphy fail randomly

### ISSUE THREAD

**Issue by EvaLiyt** [LinguaPhylo/linguaPhylo#492]
Sometimes resampling birthDeathOnRootAgeAndTaxa.lphy would fail and give the error message:
```
org.opentest4j.AssertionFailedError: Resample birthDeathOnRootAgeAndTaxa.lphy, but the returned values  ==> expected: <34> but was: <0>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:560)
	at app//lphy.base.LPhyExamplesTest.testLPhyExamplesInDir(LPhyExamplesTest.java:92)
	at app//lphy.base.LPhyExamplesTest.testLPhyExamplesRun(LPhyExamplesTest.java:37)
	at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by walterxie** [comment]
https://github.com/LinguaPhylo/linguaPhylo/commit/2bf4aeeea90ab6a36c19d692ba03c805a1fe2fb4

**Comment by walterxie** [comment]
And birthDeathRhoSampling.lphy

**Comment by walterxie** [comment]
Due to randomness.

**Comment by walterxie** [comment]
Another problem about BD:
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at lphy.base.evolution.tree.TimeTreeNode.<init>(TimeTreeNode.java:23)
	at lphy.base.evolution.birthdeath.FullBirthDeathTree.doBirth(FullBirthDeathTree.java:145)
	at lphy.base.evolution.birthdeath.FullBirthDeathTree.sample(FullBirthDeathTree.java:116)
	at lphy.base.evolution.birthdeath.BirthDeathSamplingTree.sample(BirthDeathSamplingTree.java:58)
	at lphy.core.model.GenerativeDistribution.generate(GenerativeDistribution.java:21)
	at lphy.core.simulator.Sampler.resample(Sampler.java:246)
	at lphy.core.simulator.Sampler.sample(Sampler.java:127)
	at lphy.base.LPhyExamplesTest.testLPhyExamplesInDir(LPhyExamplesTest.java:89)
	at lphy.base.LPhyExamplesTest.testLPhyExamplesRun(LPhyExamplesTest.java:37)
```
