### ISSUE TITLE
Error while running phylonco-lphy-examples

### ISSUE THREAD

**Issue by CSTE7007** [LinguaPhylo/linguaPhylo#521]
As mentioned here at https://linguaphylo.github.io/extensions/ I tried to use LPhy extension [Phylonco](https://github.com/bioDS/beast-phylonco) and follow the steps of loading example [phylonco-lphy-examples.zip](https://github.com/bioDS/beast-phylonco/releases/download/v1.0.0/phylonco-lphy-examples.zip) as bellow at `Loading examples` section:
> ### Loading examples
> Examples can be found in the releases page of the extension. To load the examples into LPhy Studio:
> 
> 1. Go to the releases page of the extension, e.g., [Phylonco releases](https://github.com/bioDS/beast-phylonco/releases) 
> 2. Download the file with the suffix *-lphy-examples.zip, e.g., [phylonco-lphy-examples.zip](https://github.com/bioDS/beast-phylonco/releases/download/v1.0.0/phylonco-lphy-examples.zip)
> 3. Unzip the *-lphy-examples.zip file inside the examples subdirectory of your LPhy installation. Your directory structure should look like this:
![image](https://github.com/user-attachments/assets/b52a71e2-a854-4233-862d-c1dae203b035)
> 4. Restart LPhy Studio, and these examples will be available through the Menu “File” -> “Example scripts” -> “extensionName”. For the Phylonco extension, this will be available through “File” -> “Example scripts” -> “phylonco”. Loading in the example script `gt16CoalErrModel.lphy` will display:
![image](https://github.com/user-attachments/assets/940dec88-6aff-4fea-af52-43986c2b297b)
> 

### **Exception and Error**

But when I downloaded the  [phylonco-lphy-examples.zip](https://github.com/bioDS/beast-phylonco/releases/download/v1.0.0/phylonco-lphy-examples.zip) following directory structure and  unziped at mentioned directory. Then while trying to open the example like the image 

![image](https://github.com/user-attachments/assets/cf376283-cc77-49f2-882a-f016ba171aba)

I faced following exception and error as bellow:
```
Gtk-Message: 13:31:31.447: Failed to load module "canberra-gtk-module"
Registering extension : lphy.base.spi.LPhyBaseImpl
Registering extension : lphy.base.spi.ValueFormatterBaseImpl
Registering extension : lphy.base.spi.SequenceTypeBaseImpl
LPhy standard sequence types : [amino acid, lphy.base.evolution.datatype.Binary@157853da, nucleotide, lphy.base.evolution.datatype.Continuous@71c3b41]
Registering extension : lphystudio.spi.LPhyStudioImpl
Registering extension : lphystudio.spi.ValueFormatterStudioImpl
Registering extension : lphy.core.spi.LPhyCoreImpl
Registering extension : lphy.core.spi.ValueFormatterCoreImpl

GenerativeDistribution : [Bernoulli, Beta, BirthDeath, BirthDeathSampling, BirthDeathSerialSampling, Categorical, Cauchy, Coalescent, Dirichlet, DiscretizeGamma, ErrorModel, Exp, ExpMarkovChain, FossilBirthDeathTree, FullBirthDeath, Gamma, Geometric, InverseGamma, LogNormal, MissingSites, MultispeciesCoalescent, NegativeBinomial, Normal, NormalGamma, PhyloBrownian, PhyloCTMC, PhyloMultivariateBrownian, PhyloOU, Poisson, RandomBooleanArray, RandomComposition, RhoSampleTree, Sequence, SimBDReverse, SimFBDAge, SimFossilsPoisson, SkylineCoalescent, StructuredCoalescent, Uniform, UniformDiscrete, Weibull, WeightedDirichlet, Yule, bSiteRates, sample]
Functions : [aminoAcids, arange, argi, bModelSet, bSiteModel, binaryDataType, binaryRateMatrix, concat2Str, concatArray, copySites, countMigrations, elementsAt, extantTaxa, extantTree, extractTrait, f81, fasta, generalTimeReversible, get, gtr, hammingWeight, hky, ifelse, intersect, invariableSites, jukesCantor, k80, length, lewisMK, localBranchRates, map, migrationMatrix, nchar, newick, ntaxa, nucleotideModel, nucleotides, parseInt, pruneTree, rangeInt, readDelim, readFasta, readNexus, rep, repArray, rmTaxa, select, selectSites, simulate, slice, sort, species, split, standard, sum, sumCols, sumRows, taxa, toDouble, unique, variableSites, wag]
LPhy data types : [Alignment, BModelSet, Boolean, Boolean[], ContinuousCharacterData, Double, Double[], Double[][], FastaAlignment, Integer, Integer[], MetaDataAlignment, NChar, Number, Number[], Number[][], Object, Object[], SequenceType, SimpleAlignment, SiteModel, String, Table, Taxa, TimeTree]
Value formatter for : [Boolean, Double, Integer, SimpleAlignment, String, TimeTree]

ANTLR Tool version 4.13.1 used for code generation does not match the current runtime version 4.11.1
ANTLR Tool version 4.13.1 used for code generation does not match the current runtime version 4.11.1
Set working dir to /home/user/lphy-studio-1.5.0/examples/phylonco

Exception in thread "AWT-EventQueue-0" lphy.core.exception.SimulatorParsingException: Found no implementation for function with name gt16 line 5 character 4
 -> gt16(freq=π,rates=rates)
    ^^^^^^^^^^^^^^^^^^^^^^^^
	at lphy.core@1.5.0/lphy.core.parser.LPhyListenerImpl$LPhyASTVisitor.visitFunction(LPhyListenerImpl.java:920)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$FunctionContext.accept(LPhyParser.java:1431)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitExpression(LPhyBaseVisitor.java:196)
	at lphy.core@1.5.0/lphy.core.parser.LPhyListenerImpl$LPhyASTVisitor.visitExpression(LPhyListenerImpl.java:487)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$ExpressionContext.accept(LPhyParser.java:1763)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at lphy.core@1.5.0/lphy.core.parser.LPhyListenerImpl$LPhyASTVisitor.visitDeterm_relation(LPhyListenerImpl.java:245)
	at lphy.core@1.5.0/lphy.core.parser.LPhyListenerImpl$LPhyASTVisitor.visitDeterm_relation(LPhyListenerImpl.java:102)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Determ_relationContext.accept(LPhyParser.java:889)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitRelation(LPhyBaseVisitor.java:77)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$RelationContext.accept(LPhyParser.java:693)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitRelation_list(LPhyBaseVisitor.java:70)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Relation_listContext.accept(LPhyParser.java:611)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitRelation_list(LPhyBaseVisitor.java:70)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Relation_listContext.accept(LPhyParser.java:611)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitRelation_list(LPhyBaseVisitor.java:70)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Relation_listContext.accept(LPhyParser.java:611)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitRelation_list(LPhyBaseVisitor.java:70)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Relation_listContext.accept(LPhyParser.java:611)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitRelation_list(LPhyBaseVisitor.java:70)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Relation_listContext.accept(LPhyParser.java:611)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitModelblock(LPhyBaseVisitor.java:63)
	at lphy.core@1.5.0/lphy.core.parser.LPhyListenerImpl$LPhyASTVisitor.visitModelblock(LPhyListenerImpl.java:118)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$ModelblockContext.accept(LPhyParser.java:533)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitStructured_input(LPhyBaseVisitor.java:28)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$Structured_inputContext.accept(LPhyParser.java:205)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyBaseVisitor.visitInput(LPhyBaseVisitor.java:21)
	at lphy.core@1.5.0/lphy.core.parser.antlr.LPhyParser$InputContext.accept(LPhyParser.java:144)
	at org.antlr.antlr4.runtime@4.11.1/org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at lphy.core@1.5.0/lphy.core.parser.LPhyParserAction.parse(LPhyParserAction.java:67)
	at lphy.core@1.5.0/lphy.core.parser.LPhyListenerImpl.parse(LPhyListenerImpl.java:53)
	at lphy.core@1.5.0/lphy.core.parser.REPL.parse(REPL.java:97)
	at lphystudio@1.5.0/lphystudio.app.graphicalmodelpanel.GraphicalModelParserDictionary.parse(GraphicalModelParserDictionary.java:20)
	at lphy.core@1.5.0/lphy.core.parser.LPhyParserDictionary.source(LPhyParserDictionary.java:120)
	at lphystudio@1.5.0/lphystudio.app.graphicalmodelpanel.GraphicalModelPanel.source(GraphicalModelPanel.java:242)
	at lphystudio@1.5.0/lphystudio.app.Utils.readFile(Utils.java:128)
	at lphystudio@1.5.0/lphystudio.app.Utils.readFileFromDir(Utils.java:102)
	at lphystudio@1.5.0/lphystudio.app.LinguaPhyloStudio.readFile(LinguaPhyloStudio.java:377)
	at lphystudio@1.5.0/lphystudio.app.LinguaPhyloStudio.lambda$createMenuItemForLPhyScript$18(LinguaPhyloStudio.java:495)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
### My configuration:
**lphy-studio-1.5.0
Ubuntu 18.04.6 LTS 64-bit | 8GB RAM
Intel® Core™ i5-3470 CPU @ 3.20GHz × 4**

**Comment by walterxie** [comment]
@CSTE7007 as I have mentioned in https://github.com/LinguaPhylo/LPhyBeast/issues/152, the current released version of phylonco is not compatible to the current release of lphy 1.5 and lphybeast 1.1. 

We are currently working on resolving this issue.

**Comment by walterxie** [comment]
https://github.com/LinguaPhylo/LPhyBeast/issues/152

**Comment by walterxie** [comment]
This is solved by new releases, please see my reply in https://github.com/LinguaPhylo/LPhyBeast/issues/152
