### ISSUE TITLE
AbstractAlignment doesn't implement getTaxon(int index) correctly after nexus call

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/linguaPhylo#89]
In studio load this example:

data {
  D = nexus(file="examples/primate.nex");
  L = nchar(D);
  taxa = taxa(D);
}
model {
  theta ~ LogNormal(meanlog=3, sdlog=1);
  T ~ Coalescent(theta=theta, taxa=taxa);
  D ~ PhyloCTMC(tree=T, L=L, Q=jukesCantor());
}

Error parsing   taxa = taxa(D);
java.lang.NullPointerException
	at lphy.evolution.alignment.AbstractAlignment.getTaxon(AbstractAlignment.java:233)
	at lphy.evolution.Taxa.getTaxonArray(Taxa.java:36)
	at lphy.evolution.alignment.AbstractAlignment.getTaxonArray(AbstractAlignment.java:238)
	at lphy.core.functions.TaxaFunction$1.getTaxonArray(TaxaFunction.java:62)
	at lphy.core.functions.TaxaFunction$1.toString(TaxaFunction.java:68)
	at lphy.graphicalModel.ValueUtils.valueToString(ValueUtils.java:121)
	at lphy.graphicalModel.Value.valueToString(Value.java:78)
	at lphy.graphicalModel.Value.toString(Value.java:71)

**Comment by walterxie** [comment]
Will it be a good time to move Taxa into Class?

**Comment by walterxie** [comment]
Also I think `TaxaCharacterMatrix` should extend `MultiDimensional` #88
